-- MySQL Script generated by MySQL Workbench
-- Wed Feb 24 19:28:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Church
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Church` ;

-- -----------------------------------------------------
-- Schema Church
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Church` DEFAULT CHARACTER SET utf8 ;
USE `Church` ;

-- -----------------------------------------------------
-- Table `Church`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Church`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Church`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `primerNombre` VARCHAR(45) NOT NULL,
  `segundoNombre` VARCHAR(45) NOT NULL,
  `primerApellido` VARCHAR(45) NOT NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `ocupacion` VARCHAR(45) NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `identidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Church`.`Tesoreria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Church`.`Tesoreria` ;

CREATE TABLE IF NOT EXISTS `Church`.`Tesoreria` (
  `idTesoreria` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTesoreria`),
  INDEX `fk_Tesoreria_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Tesoreria_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Church`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Church`.`TipoCargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Church`.`TipoCargo` ;

CREATE TABLE IF NOT EXISTS `Church`.`TipoCargo` (
  `idTipoCargo` INT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Church`.`Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Church`.`Cargo` ;

CREATE TABLE IF NOT EXISTS `Church`.`Cargo` (
  `idCargo` INT NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `TipoCargo_idTipoCargo` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCargo`),
  INDEX `fk_Cargo_TipoCargo1_idx` (`TipoCargo_idTipoCargo` ASC) VISIBLE,
  INDEX `fk_Cargo_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Cargo_TipoCargo1`
    FOREIGN KEY (`TipoCargo_idTipoCargo`)
    REFERENCES `Church`.`TipoCargo` (`idTipoCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Church`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Church`.`tipoEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Church`.`tipoEvento` ;

CREATE TABLE IF NOT EXISTS `Church`.`tipoEvento` (
  `idTipoEvento` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Church`.`Eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Church`.`Eventos` ;

CREATE TABLE IF NOT EXISTS `Church`.`Eventos` (
  `idEventos` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `lugar` VARCHAR(45) NOT NULL,
  `tipoEvento_idTipoEvento` INT NOT NULL,
  `Cargo_idCargo` INT NOT NULL,
  PRIMARY KEY (`idEventos`),
  INDEX `fk_Eventos_tipoEvento1_idx` (`tipoEvento_idTipoEvento` ASC) VISIBLE,
  INDEX `fk_Eventos_Cargo1_idx` (`Cargo_idCargo` ASC) VISIBLE,
  CONSTRAINT `fk_Eventos_tipoEvento1`
    FOREIGN KEY (`tipoEvento_idTipoEvento`)
    REFERENCES `Church`.`tipoEvento` (`idTipoEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventos_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `Church`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Church`.`Movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Church`.`Movimiento` ;

CREATE TABLE IF NOT EXISTS `Church`.`Movimiento` (
  `idMovimiento` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `concepto` VARCHAR(45) NULL,
  `monto` FLOAT NULL,
  `tipoMovimiento` VARCHAR(45) NULL,
  `Tesoreria_idTesoreria` INT NOT NULL,
  PRIMARY KEY (`idMovimiento`),
  INDEX `fk_Movimiento_Tesoreria1_idx` (`Tesoreria_idTesoreria` ASC) VISIBLE,
  CONSTRAINT `fk_Movimiento_Tesoreria1`
    FOREIGN KEY (`Tesoreria_idTesoreria`)
    REFERENCES `Church`.`Tesoreria` (`idTesoreria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Church`.`ReporteTesoreria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Church`.`ReporteTesoreria` ;

CREATE TABLE IF NOT EXISTS `Church`.`ReporteTesoreria` (
  `idReporteTesoreria` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `Movimiento_idMovimiento` INT NOT NULL,
  PRIMARY KEY (`idReporteTesoreria`),
  INDEX `fk_ReporteTesoreria_Movimiento1_idx` (`Movimiento_idMovimiento` ASC) VISIBLE,
  CONSTRAINT `fk_ReporteTesoreria_Movimiento1`
    FOREIGN KEY (`Movimiento_idMovimiento`)
    REFERENCES `Church`.`Movimiento` (`idMovimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Church`.`Ministerio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Church`.`Ministerio` ;

CREATE TABLE IF NOT EXISTS `Church`.`Ministerio` (
  `idMinisterio` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMinisterio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Church`.`ReporteMinisterio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Church`.`ReporteMinisterio` ;

CREATE TABLE IF NOT EXISTS `Church`.`ReporteMinisterio` (
  `idReporteMinisterio` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `Ministerio_idMinisterio` INT NOT NULL,
  PRIMARY KEY (`idReporteMinisterio`),
  INDEX `fk_ReporteMinisterio_Ministerio1_idx` (`Ministerio_idMinisterio` ASC) VISIBLE,
  CONSTRAINT `fk_ReporteMinisterio_Ministerio1`
    FOREIGN KEY (`Ministerio_idMinisterio`)
    REFERENCES `Church`.`Ministerio` (`idMinisterio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Church`.`Ministerio_has_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Church`.`Ministerio_has_Usuario` ;

CREATE TABLE IF NOT EXISTS `Church`.`Ministerio_has_Usuario` (
  `Ministerio_idMinisterio` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  INDEX `fk_Ministerio_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Ministerio_has_Usuario_Ministerio1_idx` (`Ministerio_idMinisterio` ASC) VISIBLE,
  CONSTRAINT `fk_Ministerio_has_Usuario_Ministerio1`
    FOREIGN KEY (`Ministerio_idMinisterio`)
    REFERENCES `Church`.`Ministerio` (`idMinisterio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ministerio_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Church`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
